/************************************/
/***  IAS ACE Cluster             ***/
/************************************/
ZCL.Cluster.SsIasAce.Cmd = new Enum({
  // command IDs received by Server
    'Arm': 0x00,  
    'Bypass': 0x01, 
    'Emergency': 0x02,  
    'Fire': 0x03,  
    'Panic': 0x04,  
    'GetZoneIDMap': 0x05,  
    'GetZoneInfo': 0x06,
    'GetPanelStatus': 0x07,
    'GetBypassedZoneList': 0x08,
    'GetZoneStatus': 0x09
});

ZCL.Cluster.SsIasAce.CmdRsp = new Enum({ 
  // Cmds, generated by Server
    'ArmRsp': 0x00,
    'GetZoneIDMapRsp': 0x01, 
    'GetZoneInfoRsp': 0x02,
    'ZoneStatusChanged': 0x03,
    'PanelStatusChanged': 0x04,
    'GetPanelStatusRsp': 0x05,
    'SetBypassedZoneList': 0x06,
    'BypassRsp': 0x07,
    'GetZoneStatusRsp': 0x08,
});

ZCL.Cluster.SsIasAce.ArmModeValue = new Enum({
    'Disarm': 0x00,
    'ArmDayHomeZonesOnly': 0x01,
    'ArmNightSleepZonesOnly': 0x02,
    'ArmAllZones': 0x03
});

ZCL.Cluster.SsIasAce.ArmNotificationValue = new Enum({
    'AllZonesDisarmed': 0x00,
    'OnlyDayHomeZonesArmed': 0x01,
    'OnlyNightSleepZonesArmed': 0x02,
    'AllZonesArmed': 0x03
});
