var colorControl = {
    attrId: {
        // Color Information Attributes set
        'CurrentHue':                   { id: 0x0000, type: 'UINT8' },
        'CurrentSaturation':            { id: 0x0001, type: 'UINT8' },
        'RemainingTime':                { id: 0x0002, type: 'UINT16' },
        'CurrentX':                     { id: 0x0003, type: 'UINT16' },
        'CurrentY':                     { id: 0x0004, type: 'UINT16' },
        'DriftCompensation':            { id: 0x0005, type: 'ENUM8' },
        'CompensationText':             { id: 0x0006, type: 'CHAR_STR' },
        'ColorTemperature':             { id: 0x0007, type: 'UINT16' },
        'ColorMode':                    { id: 0x0008, type: 'ENUM8' },
        // Defined Primaries Inofrmation Attribute Set
        'NumPrimaries':                 { id: 0x0010, type: 'UINT8' },
        'Primary1X':                    { id: 0x0011, type: 'UINT16' },
        'Primary1Y':                    { id: 0x0012, type: 'UINT16' },
        'Primary1Intensity':            { id: 0x0013, type: 'UINT8' },
        'Primary2X':                    { id: 0x0015, type: 'UINT16' },
        'Primary2Y':                    { id: 0x0016, type: 'UINT16' },
        'Primary2Intensity':            { id: 0x0017, type: 'UINT8' },
        'Primary3X':                    { id: 0x0019, type: 'UINT16' },
        'Primary3Y':                    { id: 0x001a, type: 'UINT16' },
        'Primary3Intensity':            { id: 0x001b, type: 'UINT8' },
        // Additional Defined Primaries Information Attribute set
        'Primary4X':                    { id: 0x0020, type: 'UINT16' },
        'Primary4Y':                    { id: 0x0021, type: 'UINT16' },
        'Primary4Intensity':            { id: 0x0022, type: 'UINT8' },
        'Primary5X':                    { id: 0x0024, type: 'UINT16' },
        'Primary5Y':                    { id: 0x0025, type: 'UINT16' },
        'Primary5Intensity':            { id: 0x0026, type: 'UINT8' },
        'Primary6X':                    { id: 0x0028, type: 'UINT16' },
        'Primary6Y':                    { id: 0x0029, type: 'UINT16' },
        'Primary6Intensity':            { id: 0x002a, type: 'UINT8' },
        // Defined Color Points Settings Attribute set
        'WhitePointX':                  { id: 0x0030, type: 'UINT16' },
        'WhitePointY':                  { id: 0x0031, type: 'UINT16' },
        'ColorPointRX':                 { id: 0x0032, type: 'UINT16' },
        'ColorPointRY':                 { id: 0x0033, type: 'UINT16' },
        'ColorPointRIntensity':         { id: 0x0034, type: 'UINT8' },
        'ColorPointGX':                 { id: 0x0036, type: 'UINT16' },
        'ColorPointGY':                 { id: 0x0037, type: 'UINT16' },
        'ColorPointGIntensity':         { id: 0x0038, type: 'UINT8' },
        'ColorPointBX':                 { id: 0x003a, type: 'UINT16' },
        'ColorPointBY':                 { id: 0x003b, type: 'UINT16' },
        'ColorPointBIntensity':         { id: 0x003c, type: 'UINT8' },
        //TODO
        'EnhancedCurrentHue':           { id: 0x4000, type: null },
        'EnhancedColorMode':            { id: 0x4001, type: null },
        'ColorLoopActive':              { id: 0x4002, type: null },
        'ColorLoopDirection':           { id: 0x4003, type: null },
        'ColorLoopTime':                { id: 0x4004, type: null },
        'ColorLoopStartEnhancedHue':    { id: 0x0000, type: null },
        'ColorLoopStoredEnhancedHue':   { id: 0x4006, type: null },
        'ColorCapabilities':            { id: 0x400A, type: null }
    },
    cmd: {
        'MoveToHue': 0x00,
        'MoveHue': 0x01,
        'StepHue': 0x02,
        'MoveToSaturation': 0x03,
        'MoveSaturation': 0x04,
        'StepSaturation': 0x05,
        'MoveToHueAndSaturation': 0x06,
        'MoveToColor': 0x07,
        'MoveColor': 0x08,
        'StepColor': 0x09,
        'MoveToColorTemp': 0x0a,
        'EnhancedMoveToHue': 0x40,
        'EnhancedMoveHue': 0x41,
        'EnhancedStepHue': 0x42,
        'EnhancedMoveToHueAndSaturation': 0x43,
        'ColorLoopSet': 0x44,
        'StopMoveStep': 0x47,
    },
    cmdRsp: null
};

module.exports = colorControl;
