var simpleMetering = {
    attrId: {
        // Reading Information Set
        'currentSummDelivered':                { id: 0x0000, type: 'UINT48' },
        'currentSummReceived':                 { id: 0x0001, type: 'UINT48' },
        'currentMaxDemandDelivered':           { id: 0x0002, type: 'UINT48' },
        'currentMaxDemandReceived':            { id: 0x0003, type: 'UINT48' },
        'dftSumm':                             { id: 0x0004, type: 'UINT48' },
        'dailyFreezeTime':                     { id: 0x0005, type: 'UINT16' },
        'powerFactor':                         { id: 0x0006, type: 'INT8' },
        'readingSnapshotTime':                 { id: 0x0007, type: 'UTC' },
        'currentMaxDemandDeliverdTime':        { id: 0x0008, type: 'UTC' },
        'currentMaxDemandReceivedTime':        { id: 0x0009, type: 'UTC' },
        'defaultUpdatePeriod':                 { id: 0x000A, type: 'UINT8' },
        'fastPollUpdatePeriod':                { id: 0x000B, type: 'UINT8' },
        'currentBlockPeriodConsumpDelivered':  { id: 0x000C, type: 'UINT48' },
        'dailyConsumpTarget':                  { id: 0x000D, type: 'UINT24' },
        'currentBlock':                        { id: 0x000E, type: 'ENUM8' },
        'profileIntervalPeriod':               { id: 0x000F, type: 'ENUM8' },
        'intervalReadReportingPeriod':         { id: 0x0010, type: null },
        'presetReadingTime':                   { id: 0x0011, type: 'UINT16' },
        'volumePerReport':                     { id: 0x0012, type: 'UINT16' },
        'flowRestriction':                     { id: 0x0013, type: 'UINT8' },
        'supplyStatus':                        { id: 0x0014, type: 'ENUM8' },
        'currentInEnergyCarrierSumm':          { id: 0x0015, type: 'UINT48' },
        'currentOutEnergyCarrierSumm':         { id: 0x0016, type: 'UINT48' },
        'inletTempreature':                    { id: 0x0017, type: 'INT24' },
        'outletTempreature':                   { id: 0x0018, type: 'INT24' },
        'controlTempreature':                  { id: 0x0019, type: 'INT24' },
        'currentInEnergyCarrierDemand':        { id: 0x001A, type: 'INT24' },
        'currentOutEnergyCarrierDemand':       { id: 0x001B, type: 'INT24' },
        'currentBlockPeriodConsumpReceived':   { id: 0x001D, type: 'UINT48' },
        'currentBlockReceived':                { id: 0x001E, type: 'UINT48' },
        // TOU Information Set
        'currentTier1SummDelivered':           { id: 0x0100, type: 'UINT48' },
        'currentTier1SummReceived':            { id: 0x0101, type: 'UINT48' },
        'currentTier2SummDelivered':           { id: 0x0102, type: 'UINT48' },
        'currentTier2SummReceived':            { id: 0x0103, type: 'UINT48' },
        'currentTier3SummDelivered':           { id: 0x0104, type: 'UINT48' },
        'currentTier3SummReceived':            { id: 0x0105, type: 'UINT48' }, 
        'currentTier4SummDelivered':           { id: 0x0106, type: 'UINT48' },
        'currentTier4SummReceived':            { id: 0x0107, type: 'UINT48' },
        'currentTier5SummDelivered':           { id: 0x0108, type: 'UINT48' },
        'currentTier5SummReceived':            { id: 0x0109, type: 'UINT48' },
        'currentTier6SummDelivered':           { id: 0x010A, type: 'UINT48' },
        'currentTier6SummReceived':            { id: 0x010B, type: 'UINT48' },
        'currentTier7SummDelivered':           { id: 0x010C, type: 'UINT48' },
        'currentTier7SummReceived':            { id: 0x010D, type: 'UINT48' },
        'currentTier8SummDelivered':           { id: 0x010E, type: 'UINT48' },
        'currentTier8SummReceived':            { id: 0x010F, type: 'UINT48' },
        'currentTier9SummDelivered':           { id: 0x0110, type: 'UINT48' },
        'currentTier9SummReceived':            { id: 0x0111, type: 'UINT48' },
        'currentTier10SummDelivered':          { id: 0x0112, type: 'UINT48' },
        'currentTier10SummReceived':           { id: 0x0113, type: 'UINT48' },
        'currentTier11SummDelivered':          { id: 0x0114, type: 'UINT48' },
        'currentTier11SummReceived':           { id: 0x0115, type: 'UINT48' },
        'currentTier12SummDelivered':          { id: 0x0116, type: 'UINT48' },
        'currentTier12SummReceived':           { id: 0x0117, type: 'UINT48' },
        'currentTier13SummDelivered':          { id: 0x0118, type: 'UINT48' },
        'currentTier13SummReceived':           { id: 0x0119, type: 'UINT48' },
        'currentTier14SummDelivered':          { id: 0x011A, type: 'UINT48' },
        'currentTier14SummReceived':           { id: 0x011B, type: 'UINT48' },
        'currentTier15SummDelivered':          { id: 0x011C, type: 'UINT48' },
        'currentTier15SummReceived':           { id: 0x011D, type: 'UINT48' },
        // Meter Status
        'status':                              { id: 0x0200, type: 'BITMAP8' },
        'remainingBattLife':                   { id: 0x0201, type: 'UINT8' },
        'hoursInOperation':                    { id: 0x0202, type: 'UINT24' },
        'hoursInFault':                        { id: 0x0203, type: 'UINT24' },
        'extendedStatus':                      { id: 0x0204, type: 'BITMAP64' },
        // Formatting
        'unitOfMeasure':                       { id: 0x0300, type: 'ENUM8' },
        'multiplier':                          { id: 0x0301, type: 'UINT24' },
        'divisor':                             { id: 0x0302, type: 'UINT24' },
        'summaFormatting':                     { id: 0x0303, type: 'BITMAP8' },
        'demandFormatting':                    { id: 0x0304, type: 'BITMAP8' },
        'historicalConsumpFormatting':         { id: 0x0305, type: 'BITMAP8' },
        'meteringDeviceType':                  { id: 0x0306, type: 'BITMAP8' },
        'siteId':                              { id: 0x0307, type: 'OCTET_STR' },
        'meterSerialNumber':                   { id: 0x0308, type: 'OCTET_STR' },
        'energyCarrierUnitOfMeas':             { id: 0x0309, type: 'ENUM8' },
        'energyCarrierSummFormatting':         { id: 0x030A, type: 'BITMAP8' },
        'energyCarrierDemandFormatting':       { id: 0x030B, type: 'BITMAP8' },
        'temperatureUnitOfMeas':               { id: 0x030C, type: 'ENUM8' },
        'temperatureFormatting':               { id: 0x030D, type: 'BITMAP8' },
        'moduleSerialNumber':                  { id: 0x030E, type: 'OCTET_STR' },
        'operatingTariffLevel':                { id: 0x030F, type: 'OCTET_STR' },
        // Historical Consumption
        'instantaneousDemand':                 { id: 0x0400, type: 'INT24' },
        'currentdayConsumpDelivered':          { id: 0x0401, type: 'UINT24' },
        'currentdayConsumpReceived':           { id: 0x0402, type: 'UINT24' },
        'previousdayConsumpDelivered':         { id: 0x0403, type: 'UINT24' },
        'previousdayConsumpReceived':          { id: 0x0404, type: 'UINT24' },
        'curPartProfileIntStartTimeDelivered': { id: 0x0405, type: 'UTC' },
        'curPartProfileIntStartTime_Received': { id: 0x0406, type: 'UTC' },
        'curPartProfileIntValueDelivered':     { id: 0x0407, type: 'UINT24' },
        'curPartProfileIntValueReceived':      { id: 0x0408, type: 'UINT24' },
        'currentDayMaxPressure':               { id: 0x0409, type: 'UINT48' },
        'currentDayMinPressure':               { id: 0x040A, type: 'UINT48' },
        'previousDayMaxPressure':              { id: 0x040B, type: 'UINT48' },
        'previousDayMinPressure':              { id: 0x040C, type: 'UINT48' },
        'currentDayMaxDemand':                 { id: 0x040D, type: 'INT24' },
        'previousDayMaxDemand':                { id: 0x040E, type: 'INT24' },
        'currentMonthMaxDemand':               { id: 0x040F, type: 'INT24' },
        'currentYearMaxDemand':                { id: 0x0410, type: 'INT24' },
        'currentdayMaxEnergyCarrDemand':       { id: 0x0411, type: 'INT24' },
        'previousdayMaxEnergyCarrDemand':      { id: 0x0412, type: 'INT24' },
        'curMonthMaxEnergyCarrDemand':         { id: 0x0413, type: 'INT24' },
        'curMonthMinEnergyCarrDemand':         { id: 0x0414, type: 'INT24' },
        'curYearMaxEnergyCarrDemand':          { id: 0x0415, type: 'INT24' },
        'curYearMinEnergyCarrDemand':          { id: 0x0416, type: 'INT24' },
        // Load Profile Configuration
        'maxNumberOfPeriodsDelivered':         { id: 0x0500, type: 'UINT8' },
        // Supply Limit
        'current_Demand_Delivered':            { id: 0x0600, type: 'UINT24' },
        'demandLimit':                         { id: 0x0601, type: 'UINT24' },
        'demandIntegrationPeriod':             { id: 0x0602, type: 'UINT8' },
        'numberOfDemandSubintervals':          { id: 0x0603, type: 'UINT8' },
        'demandLimitArmDuration':              { id: 0x0604, type: 'UINT16' },
        // Block Information (Delivered)
            //TODO
        // Alarms
        'genericAlarmMask':                    { id: 0x0800, type: 'BITMAP16' },
        'electricityAlarmMask':                { id: 0x0801, type: 'BITMAP32' },
        'genFlowPressureAlarmMask':            { id: 0x0802, type: 'BITMAP16' },
        'waterSpecificAlarmMask':              { id: 0x0803, type: 'BITMAP16' },
        'heatCoolSpecificAlarmMASK':           { id: 0x0804, type: 'BITMAP16' },
        'gasSpecificAlarmMask':                { id: 0x0805, type: 'BITMAP16' },
        'extendedGenericAlarmMask':            { id: 0x0806, type: 'BITMAP48' }, 
        'manufactureAlarmMask':                { id: 0x0807, type: 'BITMAP16' }, 
        // Block Information (Received)
            //TODO
        // Meter Billing Attribute Set
        'billToDate':                          { id: 0x0A00, type: 'UINT32' },
        'billToDateTimeStamp':                 { id: 0x0A01, type: 'UTC' },
        'projectedBill':                       { id: 0x0A02, type: 'UINT32' },
        'projectedBillTimeStamp':              { id: 0x0A03, type: 'UTC' },
        // Notification Attribute Set
        'notification_Control_Flags':          { id: 0x0000, type: 'BITMAP32' },
        'notification_Flags':                  { id: 0x0001, type: 'BITMAP32' },
        'price_Notification_Flags':            { id: 0x0002, type: 'BITMAP32' },
        'calendar_Notification_Flags':         { id: 0x0003, type: 'BITMAP32' },
        'pre_Pay_Notification_Flags':          { id: 0x0004, type: 'BITMAP32' },
        'device_Management_Flags':             { id: 0x0005, type: 'BITMAP32' },
        // Mirror Configuration
        'changeReportingProfile':              { id: 0x0100, type: null }
    },
    cmd: {
        'getProfile': 0x0000,
        'reqMirror': 0x0001,
        'mirrorRem': 0x0002,
        'reqFastPollMode': 0x0003,
        'getSnapshot': 0x0004,
        'takeSnapshot': 0x0005,
        'mirrorReportAttrRsp': 0x0006
    },
    cmdRsp: {
        'getProfileRsp': 0x0000,
        'reqMirrorRsp': 0x0001,
        'mirrorRemRsp': 0x0002,
        'reqFastPollModeRsp': 0x0003,
        'getSnapshotRsp': 0x0004
    }
};

module.exports = simpleMetering;
